apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://github.com/Kerwood/managment-apps-argo-repo'
    path: applications/ingress-nginx
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: 'https://c1b8f3e1-f17a-4093-95c4-ce43ff69b150.k8s.ondigitalocean.com'
    namespace: ingress-nginx
  syncPolicy:
    automated:
      prune: true
      selfHeal: true